"""Add score column to ratings table

Revision ID: 463d00dc4144
Revises: 
Create Date: 2025-01-30 21:31:24.746689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463d00dc4144'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('feedback', sa.String(), nullable=True))
    op.drop_column('ratings', 'review')
    op.drop_column('ratings', 'rating')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('ratings', sa.Column('rating', sa.INTEGER(), nullable=False))
    op.add_column('ratings', sa.Column('review', sa.TEXT(), nullable=True))
    op.drop_column('ratings', 'feedback')
    op.drop_column('ratings', 'score')
    # ### end Alembic commands ###
